# Generated by Django 3.1.6 on 2021-02-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_orden_ordentext'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='productos/qr_codes/'),
        ),
    ]
