# Generated by Django 3.1.6 on 2021-02-20 21:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_producto_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='codigo',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
